include:
  - component: $CI_SERVER_FQDN/components/dependency-scanning/main@0.5.0

stages:
    - build
    - test
    - deploy

image: python:slim-buster

build_job:
    stage: build
    script:
        - pip install -r requirements.txt

deploy_stage:
    stage: deploy
    before_script: apt-get update -y && apt-get install -y curl
    script:
        - curl -X POST -d '{}' $DEPLOY_HOOK
    rules:
        - if: '$SKIP_DEPLOY == "true"'
          when: never
        - when: on_success