stages:
    - build
    - scan
    - deploy

image: python:slim-buster

build_job:
    stage: build
    script:
        - pip install -r requirements.txt

safety_check:
    stage: scan
    before_script: pip install safety
    script: safety check -r requirements.txt --full-report > safety-report.html
    artifacts:
        paths:
            - safety-report.html
        when: always
    

deploy_stage:
    stage: deploy
    script:
        - curl -X POST -d '{}' $DEPLOY_HOOK